name: Generate Stubs

on:
  push:
    paths:
      - 'proto/**'

jobs:
  generate-stubs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install protoc
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Generate stubs
      run: make generate-stubs
